#!/bin/bash
# train_3dgs.sh — Train 3D Gaussian Splatting from COLMAP output using nerfstudio
#
# Usage:
#   ./train_3dgs.sh [colmap_workspace]
#
# Default colmap_workspace: ~/midterm_reconstruction
# The workspace must contain:
#   sparse/0/  — cameras.bin + images.bin + points3D.bin  (or .txt equivalents)
# Images must be in:
#   ~/midterm_flight_data/rgb/  (nerfstudio reads the image paths from images.bin)
#
# Output:
#   ~/midterm_3dgs_output/   — training checkpoints and config
#   ~/midterm_3dgs_export/   — exported .ply splat file

set -e

COLMAP_WS="${1:-$HOME/midterm_reconstruction}"
OUTPUT_DIR="$HOME/midterm_3dgs_output"
EXPORT_DIR="$HOME/midterm_3dgs_export"
MAX_ITERS=15000

# ── Validate inputs ────────────────────────────────────────────────────────────

if [ ! -d "$COLMAP_WS" ]; then
    echo "ERROR: COLMAP workspace not found: $COLMAP_WS"
    echo "  Run run_colmap.sh or create_colmap_from_poses.py first."
    exit 1
fi

SPARSE_DIR="$COLMAP_WS/sparse/0"
if [ ! -d "$SPARSE_DIR" ]; then
    echo "ERROR: sparse/0/ not found in $COLMAP_WS"
    echo "  Expected: $SPARSE_DIR/{cameras,images,points3D}.{bin,txt}"
    exit 1
fi

# Check at least one of the required files exists (binary or text format)
if ! ls "$SPARSE_DIR"/cameras.{bin,txt} "$SPARSE_DIR"/images.{bin,txt} 2>/dev/null | grep -q .; then
    echo "ERROR: No cameras/images files found in $SPARSE_DIR"
    exit 1
fi

# ── Check nerfstudio ───────────────────────────────────────────────────────────

if ! command -v ns-train &>/dev/null; then
    echo "ERROR: ns-train not found. Install with:"
    echo "  pip install nerfstudio --break-system-packages"
    exit 1
fi

echo "=== 3D Gaussian Splatting Training ==="
echo "  COLMAP workspace : $COLMAP_WS"
echo "  Max iterations   : $MAX_ITERS"
echo "  Output dir       : $OUTPUT_DIR"
echo "  Export dir       : $EXPORT_DIR"
echo ""

mkdir -p "$OUTPUT_DIR" "$EXPORT_DIR"

# ── Train ─────────────────────────────────────────────────────────────────────
# splatfacto is nerfstudio's 3DGS implementation backed by gsplat.
# --pipeline.datamanager.data points to the COLMAP workspace.
# --pipeline.model.cull-alpha-thresh 0.005 retains more Gaussians during densification.
# --output-dir puts checkpoints under $OUTPUT_DIR/<timestamp>/splatfacto/

echo "=== Starting training ==="
ns-train splatfacto \
    --data "$COLMAP_WS" \
    --max-num-iterations "$MAX_ITERS" \
    --output-dir "$OUTPUT_DIR" \
    --pipeline.model.cull-alpha-thresh 0.005 \
    --vis tensorboard \
    2>&1 | tee "$OUTPUT_DIR/train.log"

# ── Find the config file generated by nerfstudio ──────────────────────────────

CONFIG_PATH=$(find "$OUTPUT_DIR" -name "config.yml" -newer "$OUTPUT_DIR/train.log" 2>/dev/null \
              | sort | tail -1)
if [ -z "$CONFIG_PATH" ]; then
    # Fallback: find any config in output dir
    CONFIG_PATH=$(find "$OUTPUT_DIR" -name "config.yml" | sort | tail -1)
fi

if [ -z "$CONFIG_PATH" ]; then
    echo ""
    echo "WARNING: Could not find config.yml in $OUTPUT_DIR"
    echo "  Export manually with:"
    echo "  ns-export gaussian-splat --load-config <path/to/config.yml> --output-dir $EXPORT_DIR"
    exit 0
fi

echo ""
echo "=== Exporting Gaussian splat ==="
echo "  Config : $CONFIG_PATH"
echo "  Output : $EXPORT_DIR"
echo ""

ns-export gaussian-splat \
    --load-config "$CONFIG_PATH" \
    --output-dir "$EXPORT_DIR"

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "=== Training + export complete ==="
echo "  Config      : $CONFIG_PATH"
echo ""
if ls "$EXPORT_DIR"/*.ply &>/dev/null; then
    for f in "$EXPORT_DIR"/*.ply; do
        SIZE=$(du -sh "$f" | cut -f1)
        echo "  Splat file  : $f  ($SIZE)"
    done
else
    echo "  Export dir  : $EXPORT_DIR"
fi
echo ""
echo "Viewer commands:"
echo "  ns-viewer --load-config $CONFIG_PATH"
echo "  # Or open the .ply in SuperSplat / PolyCam / any .ply viewer"
